### ISSUE TITLE
iOS throws an exception

### ISSUE THREAD

**Issue by baabale** [Subhi-Khalife/social_media_recorder#1]
Please, kindly check if this plugin works on iOS devices, I have been trying to use it on Android, it works fine but on iOS, it keeps destroying in the build process.

**Comment by Subhi-Khalife** [comment]
@baabale 
Thanx for your feedback
crash when click record button ? 
or can't make build for app

**Comment by baabale** [comment]
@Subhi-Khalife, thanks for your reply.
The app can't make build at all. The problem generated the record_mp3 plugin you've used. I've tried to use that plugin before, but it kept throwing an error whenever I use it with iOS.

Here is the error message:
```
 ** BUILD FAILED **
Xcode's output:
↳
ld: in /Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a(lame.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
2
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
warning: no rule to process file '/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a' of type 'archive.ar' for architecture 'arm64' (in target 'record_mp3' from project 'Pods')
warning: no rule to process file '/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a' of type 'archive.ar' for architecture 'x86_64' (in target 'record_mp3' from project 'Pods')

```

**Comment by Subhi-Khalife** [comment]
@baabale 
are you using beta version from flutter ?
if yes try it on stable version

**Comment by baabale** [comment]
@Subhi-Khalife 
No, I am not using the beta version.

`Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1`

**Comment by baabale** [comment]
> @baabale
> are you using beta version from flutter ?
> if yes try it on stable version

No, I am not using the beta version.

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git Framework • revision 77d935af4d (3 weeks ago) • 2021-12-16 08:37:33 -0800 Engine • revision 890a5fca2e Tools • Dart 2.15.1

**Comment by Subhi-Khalife** [comment]
> @baabale are you using beta version from flutter ? if yes try it on stable version

**Comment by baabale** [comment]
Why did you close the issue?! It has not yet resolved it.

I am using the stable channel and it still throws the exception while building the app on iOS device.

**Comment by Subhi-Khalife** [comment]
> Why did you close the issue?! It has not yet resolved it.
> 
> I am using the stable channel and it still throws the exception while building the app on iOS device.

I'm so sorry, but I hit the close button Accidentally 
And I will try to solve this problem as soon as possible
And I renew my sorry

**Comment by baabale** [comment]
No problem at all! I will highly appreciate it if you can fix it as soon as possible, cuz I am now building an app where this feature is mandatory.

**Comment by Subhi-Khalife** [comment]
> No problem at all! I will highly appreciate it if you can fix it as soon as possible, cuz I am now building an app where this feature is mandatory.

don't worry about it complete your work on android and when i fix this problem mentioned to update the package

**Comment by baabale** [comment]
@Subhi-Khalife 
Have you resolved the issue?

**Comment by Subhi-Khalife** [comment]
> @Subhi-Khalife Have you resolved the issue?

I need mac and My computer has problems at the moment
If you can help me, thank you very much 
or wait Tomorrow or after Tomorrow until get the laptop from my friend

**Comment by baabale** [comment]
> > @Subhi-Khalife Have you resolved the issue?
> 
> I need mac and My computer has problems at the moment If you can help me, thank you very much or wait Tomorrow or after Tomorrow until get the laptop from my friend

Well, where can I get in touch with you? I will give you an access to my MacBook to track the bugs and we can give a hand.

What do you think?

**Comment by Subhi-Khalife** [comment]
@baabale 
I sent meesage to you on your email

**Comment by Subhi-Khalife** [comment]
@baabale 
contact with me on telegram to make share screen with you this my account on telegram
@SubhiKhalifeh

**Comment by Subhi-Khalife** [comment]
@baabale 
the problem was fixed try install new version from package and tell me if this issue fixed on your project  and 
tell me if there are any problem  tell me

**Comment by Subhi-Khalife** [comment]
If any one faced same issue just update to the latest version

**Comment by baabale** [comment]
> @baabale
> the problem was fixed try install new version from package and tell me if this issue fixed on your project and
> tell me if there are any problem tell me

Sorry, I am still having the bug:

`Launching lib/main.dart on iPhone 12 Pro in debug mode...
lib/main.dart:1
Xcode build done.                                            8.4s
Failed to build iOS app
Error output from Xcode build:
↳
    objc[14439]: Class AMSupportURLConnectionDelegate is implemented in both /usr/lib/libauthinstall.dylib (0x1fb196b90) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107b3c2c8). One of the two will be used. Which one is undefined.
    objc[14439]: Class AMSupportURLSession is implemented in both /usr/lib/libauthinstall.dylib (0x1fb196be0) and /Library/Apple/System/Library/PrivateFrameworks/MobileDevice.framework/Versions/A/MobileDevice (0x107b3c318). One of the two will be used. Which one is undefined.
    ** BUILD FAILED **
Xcode's output:
↳
    /Users/baabale/Documents/development/apps/maashka/ios/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Wpointer-to-int-cast]
                                 NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                                  ^~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/baabale/Documents/development/apps/maashka/ios/Pods/Reachability/Reachability.m:465:63: warning: cast to smaller integer type 'unsigned int' from 'Reachability *' [-Wpointer-to-int-cast]
                                 NSStringFromClass([self class]), (unsigned int) self, [self currentReachabilityFlags]];
                                                                  ^~~~~~~~~~~~~~~~~~~
    1 warning generated.
/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/SwiftRecordMp3Plugin.swift:22:9: warning: result of 'SwiftRecordMp3Plugin' initializer is unused
            SwiftRecordMp3Plugin(registrar: registrar)
            ^                   ~~~~~~~~~~~~~~~~~~~~~~
/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/SwiftRecordMp3Plugin.swift:22:9: warning: result of 'SwiftRecordMp3Plugin' initializer is unused
            SwiftRecordMp3Plugin(registrar: registrar)
            ^                   ~~~~~~~~~~~~~~~~~~~~~~
ld: in /Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a(lame.o), building for iOS Simulator, but linking in object file built for iOS, for architecture arm64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/GoogleAppMeasurement.build/InputFileList-7AE32662A513CB56E4449389F0A03E1F-GoogleAppMeasurement-xcframeworks-input-files-45abe2dc9df407c789b1dd0f4b1c0469-resolved.xcfilelist'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/GoogleAppMeasurement.build/OutputFileList-7AE32662A513CB56E4449389F0A03E1F-GoogleAppMeasurement-xcframeworks-output-files-12d5799913e3ca08fce5e9de579a30c9-resolved.xcfilelist'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/PromisesObjC.build/Script-0510341864B31EA26531DDD1397DE3DA.sh'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/GoogleAppMeasurement.build/Script-7AE32662A513CB56E4449389F0A03E1F.sh'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseAnalytics.build/InputFileList-90FD63C35034F337E77CEF95B589FCB9-FirebaseAnalytics-xcframeworks-input-files-974718e0836f6e1cc618c8d35d2f9f79-resolved.xcfilelist'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseAnalytics.build/OutputFileList-90FD63C35034F337E77CEF95B589FCB9-FirebaseAnalytics-xcframeworks-output-files-a42a5bf7f9730b60826e8a9253f977a5-resolved.xcfilelist'
    note: Removed stale file '/Users/baabale/Library/Developer/Xcode/DerivedData/Runner-bvbuyvvlmcjqlkcjtpnwwoakoxfu/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/FirebaseAnalytics.build/Script-90FD63C35034F337E77CEF95B589FCB9.sh'
    /Users/baabale/Documents/development/apps/maashka/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'Reachability' from project 'Pods')
    /Users/baabale/Documents/development/apps/maashka/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.2.99. (in target 'FMDB' from project 'Pods')
warning: no rule to process file '/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a' of type 'archive.ar' for architecture 'arm64' (in target 'record_mp3' from project 'Pods')
warning: no rule to process file '/Users/baabale/Documents/development/flutter/.pub-cache/hosted/pub.dartlang.org/record_mp3-3.0.0/ios/Classes/Fat-Lame/lib/libmp3lame.a' of type 'archive.ar' for architecture 'x86_64' (in target 'record_mp3' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 12 Pro.
Exited (sigterm)
`

**Comment by Subhi-Khalife** [comment]
@baabale 
Can contact with me on telegram to try solve this problem and know what the happened

**Comment by Subhi-Khalife** [comment]
All the problems was fixed 
if you face any problems just update to the latest version from package 
thanks for
@baabale 
to help me to fix and discover the problems
